import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ThemeProvider from "../providers/ThemeProvider";
import { Toaster } from "sonner";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning className={`min-h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>
          <ThemeProvider>{children}</ThemeProvider>
          {/* {children} */}
          <Toaster
            position="top-right"
            closeButton
            expand
            theme="dark"
            toastOptions={{
              classNames: {
                toast: "!bg-zinc-950 !text-white !border !border-yellow-500",
                title: "!text-white",
                description: "!text-zinc-300",
                success: "!bg-zinc-950 !border-l-4 !border-l-yellow-400",
                error: "!bg-zinc-950 !border-l-4 !border-l-red-500",
                warning: "!bg-zinc-950 !border-l-4 !border-l-yellow-500",
                info: "!bg-zinc-950 !border-l-4 !border-l-blue-500",
              },
            }}
          />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
